//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEAUTIST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Report = new HashSet<Report>();
        }
    
        public int Id { get; set; }
        public string Addres { get; set; }
        public Nullable<int> Rooms { get; set; }
        public Nullable<int> Square { get; set; }
        public Nullable<System.DateTime> ComingDate { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> JobTypeId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual JobType JobType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report { get; set; }
    }
}
